DROP TABLE IF EXISTS FORUM_MESSAGE;
DROP TABLE IF EXISTS FORUM;


CREATE TABLE FORUM (
    ID         			 INTEGER UNSIGNED  NOT NULL  AUTO_INCREMENT,
    NAME             VARCHAR(50)       NOT NULL, 
    DESCRIPTION      VARCHAR(100)      NOT NULL,

    PRIMARY KEY (ID)
)
ENGINE=InnoDB DEFAULT CHARACTER SET latin1
    COLLATE latin1_general_cs AUTO_INCREMENT=0;

CREATE TABLE MESSAGE (
    ID                 BIGINT UNSIGNED   NOT NULL  AUTO_INCREMENT,
    PARENT_ID          BIGINT UNSIGNED   NULL,
    FORUM_ID           INTEGER UNSIGNED  NOT NULL,
    SUBJECT            VARCHAR(100)      NOT NULL,
    MESSAGE_TEXT       TEXT              NOT NULL,
    MESSAGE_DATE       TIMESTAMP         NOT NULL  DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (ID),

    FOREIGN KEY (PARENT_ID)
        REFERENCES MESSAGE(ID)
)
ENGINE=InnoDB DEFAULT CHARACTER SET latin1
    COLLATE latin1_general_cs AUTO_INCREMENT=0;

